apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-service
  namespace: school-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-service
  template:
    metadata:
      labels:
        app: club-service
    spec:
      containers:
      - name: club-service
        image: ${DOCKER_HUB_USER}/club-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://host.docker.internal:3306/club_service_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://host.docker.internal:8761/eureka/"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: club-service
  namespace: school-platform
spec:
  selector:
    app: club-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
